
spring.application.name=notification-service
#eureka.instance.instance-id=${spring.application.name}:${random.uuid}
spring.config.import=optional:consul:

management.endpoints.web.exposure.include=*
server.port=${SERVICE_PORT:0}
#server.port=0

management.server.port=9906

# Indispensable si le port management est différent
spring.cloud.consul.discovery.health-check-port=${management.server.port}
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.register-health-check-service=false
spring.cloud.consul.discovery.management-register=false


spring.cloud.compatibility-verifier.enabled=false

#spring.main.allow-bean-definition-overriding=true

spring.cloud.consul.discovery.enabled=false
spring.cloud.consul.discovery.service-name=notification-service
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}

spring.cloud.consul.discovery.prefer-ip-address=true

spring.cloud.consul.config.enabled=false
#spring.cloud.consul.config.name=notification-service
#spring.cloud.consul.config.watch.enabled=false
#spring.cloud.consul.config.format=properties

spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=${CONSUL_PORT:8500}

spring.cloud.function.definition=processOrderNotification
spring.cloud.stream.function.definition=processOrderNotification

# La destination doit être EXACTEMENT la même que celle de l'émetteur
spring.cloud.stream.bindings.processOrderNotification-in-0.destination=order-notification-exchange
spring.cloud.stream.bindings.processOrderNotification-in-0.group=notification-service-group
spring.cloud.stream.bindings.processOrderNotification-in-0.content-type=text/plain
spring.cloud.stream.rabbit.bindings.processOrderNotification-in-0.consumer.exchangeType=topic

spring.cloud.stream.rabbit.bindings.processOrderNotification-in-0.consumer.bindingRoutingKey=my.routing.key
spring.security.strategy=mode_inheritable_thread_local

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
###spring.sleuth.integration.enabled=true
###spring.zipkin.base-url=http://localhost:9411/
###spring.sleuth.sampler.probability=1

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_REDIS_PASSWORD:123}
#Enable caching
spring.cache.type=redis

spring.main.allow-bean-definition-overriding=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KC_HOST:localhost}:${KC_PORT:7080}/realms/microservices-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KC_HOST:localhost}:${KC_PORT:7080}/realms/microservices-realm/protocol/openid-connect/certs
