version: '3'
services:
  discovery:
    image: hashicorp/consul:latest
    ports:
       - '8500:8500'
 
  customer-service:
    #image: customer-service
    build: ./customer-service
    container_name: cn-customer-service
    #restart: always
    environment:
        - JAVA_TOOL_OPTIONS=
        - DCONSUL_HOST=discovery 
        - Ddiscovery_PORT=8500
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8500/actuator/health" ]
        interval: 10s
        retries: 4	
    depends_on:
        - discovery
      #- service-auth

  inventory-service:
    build: ./inventory-service
    #image: im-inventory-service
    container_name: cn-inventory-service
    environment:
       - JAVA_TOOL_OPTIONS=
       - DCONSUL_HOST=discovery
       - DCONSUL_PORT=8500
    depends_on:
      - discovery

  product-serviceb:
    build: ./product-serviceb
    #image: im-product-serviceb
    container_name: cn-product-serviceb
    environment:
        - JAVA_TOOL_OPTIONS=
        - DCONSUL_HOST=discovery
        - DCONSUL_PORT=8500
    depends_on:
        - discovery

  order-serviceb:
     build: ./order-serviceb
     #image: im-order-serviceb
     container_name: cn-order-serviceb
     environment:
        - JAVA_TOOL_OPTIONS=
        - DCONSUL_HOST=discovery
        - DCONSUL_PORT=8500
     depends_on:
        - discovery

  payment-service:
     build: ./payment-service
     #image: im-payment-service
     container_name: cn-payment-service
     environment:
        - JAVA_TOOL_OPTIONS=
        - DCONSUL_HOST=discovery
        - DCONSUL_PORT=8500
     depends_on:
        - discovery

  notification-service:
     build: ./notification-service
     #image: im-notification-service
     container_name: cn-notification-service
     environment:
        - JAVA_TOOL_OPTIONS=
        - DCONSUL_HOST=discovery
        - DCONSUL_PORT=8500
     depends_on:
        - discovery
  
  api-gateway-service:
     build: ./api-gateway-service
     #image: im-api-gateway-service
     container_name: cn-api-gateway-service
     ports:
       - 8080:8080
     environment:
       - JAVA_TOOL_OPTIONS=
       - DCONSUL_HOST=discovery
       - DCONSUL_PORT=8500
     depends_on:
      - discovery