#version: '3.9'
services:
  docker-mysql:
    image: mysql
    container_name: cn-mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:3306/health" ]
        interval: 10s
        retries: 10
    restart: always
    networks:
      - net-mysql

  discovery:
    image: hashicorp/consul:latest
    container_name: discovery
    environment:
        - CONUL_BIND_INTERFACE=eth0
    volumes:
        - consul_data:/consul/data
    ports:
        - '8400:8400'
        - '8500:8500'
        - '8600:8600'
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8501/health" ]
        interval: 10s
        retries: 10
    restart: always
    depends_on:
       - rabbitmq
           #condition: service_started
    networks:
          - net-mysql
  
  config-service:
     build: ./config-service
     container_name: config-service
     image: im-config-service
     ports:
        - "8889:8889"
     environment:
        - CONSUL_HOST=discovery
        - CONSUL_PORT=8500
        - CONFIG_SERVICE_PORT=8889
     networks:
       - net-mysql 
     healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8889/actuator/health" ]
        interval: 10s
        retries: 10
     depends_on:
         - discovery
             # condition: service_healthy
    # networks:
    #   - micros     
  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: rabbitmq
    ports:
      - 5673:5672
      - 15673:15672
    depends_on:
      - docker-mysql

  inventory-service:
     build: ./inventory-service
     #image: im-inventory-service
     container_name: cn-inventory-service
     environment:
       - JAVA_TOOL_OPTIONS=
       - CONSUL_HOST=discovery
       - CONSUL_PORT=8500
       - CONFIG_SERVICE_URL=config-service
       - CONFIG_SERVICE_PORT=8889
       - DOCKER_MYSQL=docker-mysql
       - MYSQL_PW  =root
       - MYSQL_USER=root
       #- SPRING_PROFILES_ACTIVE=docker  
       - SPRING_DATA_SOURCE_URL=jdbc:mysql://docker-mysql:3306/inventory-ser?createDatabaseIfNotExist=true
       - RABBITMQ_HOST=rabbitmq
       - RABBITMQ_PW=5673
     healthcheck:
       test: [ "CMD", "curl", "-f", "http://localhost:8500/actuator/health" ]
       interval: 10s
       retries: 4
     networks:
       - net-mysql 
     depends_on:
        config-service:
            condition: service_healthy
             
volumes:
   consul_data:
#  customer-service:
#    #image: im-customer-service
#    build: ./customer-service
#    container_name: cn-customer-service
#    #restart: always
#    environment:
#        - JAVA_TOOL_OPTIONS=
#        - CONSUL_HOST=discovery 
#        - CONSUL_PORT=8500
#        - CONFIG_SERVICE_URL=config-service
#        - CONFIG_SERVICE_PORT=8888
##    healthcheck:
##        test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
##        interval: 10s
##        retries: 4
#    depends_on:
#       config-service:
#          condition: service_started
#  product-serviceb:
#    build: ./product-serviceb
#    #image: im-product-serviceb
#    container_name: cn-product-serviceb
#    environment:
#        - JAVA_TOOL_OPTIONS=
#        - CONSUL_HOST=discovery
#        - CONSUL_PORT=8500
#        - CONFIG_SERVICE_URL=config-service
#        - CONFIG_SERVICE_PORT=8888
##    healthcheck:
##        test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
##        interval: 10s
##        retries: 4
#    depends_on:
#       config-service:
#          condition: service_healthy
#  order-serviceb:
#     build: ./order-serviceb
#     #image: im-order-serviceb
#     container_name: cn-order-serviceb
#     environment:
#        - JAVA_TOOL_OPTIONS=
#        - CONSUL_HOST=discovery
#        - CONSUL_PORT=8500
#        - CONFIG_SERVICE_URL=config-service
##     healthcheck:
##        test: [ "CMD", "curl", "-f", "http://localhost:8500/actuator/health" ]
##        interval: 10s
##        retries: 4
#     depends_on:
#        config-service:
#           condition: service_healthy
#  payment-service:
#     build: ./payment-service
#     #image: im-payment-service
#     container_name: cn-payment-service
#     environment:
#        - JAVA_TOOL_OPTIONS=
#        - CONSUL_HOST=discovery
#        - CONSUL_PORT=8500
#        - CONFIG_SERVICE_URL=config-service
##     healthcheck:
##        test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
##        interval: 10s
##        retries: 4
#     depends_on:
#        config-service:
#           condition: service_healthy
#  notification-service:
#     build: ./notification-service
#     #image: im-notification-service
#     container_name: cn-notification-service
#     environment:
#        - JAVA_TOOL_OPTIONS=
#        - CONSUL_HOST=discovery
#        - CONSUL_PORT=8500
#        - CONFIG_SERVICE_URL=config-service
##     healthcheck:
##         test: [ "CMD", "curl", "-f", "http://localhost:8500/actuator/health" ]
##         interval: 10s
##         retries: 4
#     depends_on:
#        config-service:
#           condition: service_healthy
#  api-gateway-service:
#     build: ./api-gateway-service
#     #image: im-api-gateway-service
#     container_name: cn-api-gateway-service
#     ports:
#       - 8080:8080
#     environment:
#       - JAVA_TOOL_OPTIONS=
#       - CONSUL_HOST=discovery
#       - CONSUL_PORT=8500
#       - CONFIG_SERVICE_URL=config-service
##     healthcheck:
##        test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
##        interval: 10s
##        retries: 4
#     depends_on:
#        config-service:
#           condition: service_healthy
networks:
   net-mysql: