server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/abdellah2188/EcommConfig.git
    consul:
      port: ${CONSUL_PORT:8500}
      host: ${CONSUL_HOST:localhost}
      config: 
        - name=config-server
        - enabled=true
        - watch:
            - enabled=false
        - format=properties            
management:
    endpoints:
       - web:
           - exposure:
                - include=*