server:
  port: ${CONFIG_PORT:8888}
spring:
  application:
    name: config-service
  cloud:
    config:
      discovery:
        enabled: true
        healthCheckPath: "/actuator/health"
      server:
        git:
          uri: https://github.com/abdellah2188/EcommConfig.git
    consul:
      port: ${CONSUL_PORT:8500}
      host: ${CONSUL_HOST:localhost}
    loadbalancer:
      ribbon:
         enabled: true	
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PW:5672}
    username: guest
    password: guest	        
management:
    endpoints:
       - web:
           - exposure:
                - include=*
